// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo1o73OV7OknNZ2BR4eYhdXmtCHZ3tNAg',
    appId: '1:51141491954:web:329f194cb50a05f3aaa46b',
    messagingSenderId: '51141491954',
    projectId: 'noyw-13e15',
    authDomain: 'noyw-13e15.firebaseapp.com',
    storageBucket: 'noyw-13e15.appspot.com',
    measurementId: 'G-P964MHSK3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg9umkJjUcPrA12TTn4iygGPtw88N7nXM',
    appId: '1:51141491954:android:84203c13caca6a99aaa46b',
    messagingSenderId: '51141491954',
    projectId: 'noyw-13e15',
    storageBucket: 'noyw-13e15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF0NZhf4c8XvrLI-pKqPX1PunOh1y56nk',
    appId: '1:51141491954:ios:8c5d35ed67a93054aaa46b',
    messagingSenderId: '51141491954',
    projectId: 'noyw-13e15',
    storageBucket: 'noyw-13e15.appspot.com',
    iosBundleId: 'com.example.myfinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF0NZhf4c8XvrLI-pKqPX1PunOh1y56nk',
    appId: '1:51141491954:ios:8c5d35ed67a93054aaa46b',
    messagingSenderId: '51141491954',
    projectId: 'noyw-13e15',
    storageBucket: 'noyw-13e15.appspot.com',
    iosBundleId: 'com.example.myfinance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKn6RTm550MRWUqgRq66garzuRel5sFpE',
    appId: '1:51141491954:web:60b1da40c23ceff0aaa46b',
    messagingSenderId: '51141491954',
    projectId: 'noyw-13e15',
    authDomain: 'noyw-13e15.firebaseapp.com',
    storageBucket: 'noyw-13e15.appspot.com',
    measurementId: 'G-PL6Y9GF9P1',
  );

}